### ISSUE TITLE
Fizzbuzz.java - syntax is atrocious

### ISSUE THREAD

**Issue by dmstrat** [TreyBMorris/FizzBuzz#1]
Please take a few minutes and clean up the syntax and formatting on this page.

**Comment by dmstrat** [comment]
Remember how we talked about formatting your code and NOT have executing code in "main"? 

 for(int i = 1; i<=100; i++)
 {
   if (i % 3 == 0)
   {
     System.out.print("Fizz");
   }
   {  // why is this here? unused scope markers
   if(i%5==0)
   { //always wrap if/else statements in scope markers even when only one line.
     System.out.print("Buzz");
   }
   else if (i % 3 != 0)
   {
     System.out.print(i);System.out.println();
   }
   } //unused pair of scope marker
 }

**Comment by dmstrat** [comment]
also, what about intent revealing variables?  what is "i % 3 == 0" intent?  or the 5 version?
bool divisibleBy3 = i % 3 == 0; 
if(divisibleBy3)
{ do work } 
if(divisibleBy5) 
{ do work } 

reads better, right?

**Comment by TreyBMorris** [comment]
Issue should hopefully be fixed, let me know if there are more fixes I need to make.

**Comment by dmstrat** [comment]
still needs work, see forked/fixed file link I sent before.

**Comment by dmstrat** [comment]
syntax looks much better.
